[package]
name = "aula1_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.37.0"

[profile.release]
debug=false
opt-level=3
codegen-units=1
lto=true
overflow-checks=false
panic="abort"